apiVersion: v1
kind: Pod 
metadata: 
  name: svc-pod
  labels: 
    app: test-1
spec:
  containers:
    - name: test-co
      image: jenkins/jenkins:latest-jdk21 
      ports:
        - containerPort: 80
          protocol: TCP
             